@api = http://localhost:3001

###
GET {{api}}}/posts

###
GET {{api}}}/posts/1

###
POST {{api}}/posts
Content-Type:  application/json

{
  "title": "Title2" ,
  "body": "blah blah blah blah blah"
}
###
DELETE {{api}}/posts/1
###
PUT {{api}}/posts/1
